# default config

#pool pool.ntp.org iburst
#initstepslew 10 pool.ntp.org
driftfile /var/lib/chrony/chrony.drift
rtcsync
cmdport 0
allow

# GPS Time Source (via gpsd SHM)
refclock SHM 0 poll 2 refid GPS precision 1e-1 offset 0.9999 delay 0.2
refclock SHM 1 poll 2 refid PPS precision 1e-7

